"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import {
  ApiError,
  createCustomer,
  toErrorMessage,
  type CustomerInput,
  type CustomerType,
} from "@/lib/api";
import {
  Button,
  Card,
  CardHeader,
  CheckboxField,
  Field,
  Notice,
  PageIntro,
  Select,
  TextArea,
  TextInput,
} from "../../_components/ui";
import {
  CUSTOMER_TYPE_OPTIONS,
  FieldErrorText,
  nullableOptionalString,
  validateEmail,
} from "../../customer-booking";

type CustomerFormState = {
  customerType: CustomerType;
  name: string;
  phone: string;
  address: string;
  email: string;
  nidOrPassport: string;
  professionOrBusiness: string;
  nomineeOrReference: string;
  notes: string;
  isActive: boolean;
};

const emptyForm: CustomerFormState = {
  address: "",
  customerType: "INDIVIDUAL",
  email: "",
  isActive: true,
  name: "",
  nidOrPassport: "",
  nomineeOrReference: "",
  notes: "",
  phone: "",
  professionOrBusiness: "",
};

export default function NewCustomerPage() {
  const router = useRouter();
  const [form, setForm] = useState<CustomerFormState>(emptyForm);
  const [isSaving, setIsSaving] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

  function validate(): boolean {
    const nextErrors: Record<string, string> = {};

    if (!form.name.trim()) {
      nextErrors.name = "Name is required.";
    }
    if (!form.phone.trim()) {
      nextErrors.phone = "Phone is required.";
    }
    if (!form.address.trim()) {
      nextErrors.address = "Address is required.";
    }
    if (!validateEmail(form.email)) {
      nextErrors.email = "Enter a valid email address or leave it blank.";
    }

    setFieldErrors(nextErrors);
    return Object.keys(nextErrors).length === 0;
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setFormError(null);

    if (!validate()) {
      return;
    }

    const payload: CustomerInput = {
      address: form.address.trim(),
      customerType: form.customerType,
      email: nullableOptionalString(form.email),
      isActive: form.isActive,
      name: form.name.trim(),
      nidOrPassport: nullableOptionalString(form.nidOrPassport),
      nomineeOrReference: nullableOptionalString(form.nomineeOrReference),
      notes: nullableOptionalString(form.notes),
      phone: form.phone.trim(),
      professionOrBusiness: nullableOptionalString(form.professionOrBusiness),
    };

    setIsSaving(true);

    try {
      const created = await createCustomer(payload);
      router.replace(`/app/customers/${created.id}`);
      router.refresh();
    } catch (caught) {
      if (caught instanceof ApiError && caught.isUnauthorized) {
        router.replace("/login");
        return;
      }

      setFormError(toErrorMessage(caught));
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between gap-3">
        <PageIntro
          title="Customers & Bookings - New Customer"
          description="Create an internal customer master record for booking control. Customer code is generated by the backend."
        />
        <Link href="/app/customers">
          <Button variant="ghost">
            <ArrowLeft aria-hidden="true" className="size-4" />
            Back to customers
          </Button>
        </Link>
      </div>

      <Card>
        <CardHeader
          title="Customer form"
          description="Address is required and customer code is not entered manually. Backend validation remains authoritative for NID/passport uniqueness checks."
        />

        <form className="mt-6 flex flex-col gap-5" onSubmit={handleSubmit}>
          <div className="grid gap-5 sm:grid-cols-2">
            <Field htmlFor="customer-type" label="Customer type" required>
              <Select
                id="customer-type"
                value={form.customerType}
                onChange={(event) =>
                  setForm((previous) => ({
                    ...previous,
                    customerType: event.target.value as CustomerType,
                  }))
                }
              >
                {CUSTOMER_TYPE_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </Select>
            </Field>

            <Field htmlFor="customer-name" label="Name" required>
              <TextInput
                id="customer-name"
                value={form.name}
                onChange={(event) =>
                  setForm((previous) => ({ ...previous, name: event.target.value }))
                }
                placeholder="Customer name"
                required
              />
              <FieldErrorText message={fieldErrors.name ?? null} />
            </Field>

            <Field htmlFor="customer-phone" label="Phone" required>
              <TextInput
                id="customer-phone"
                value={form.phone}
                onChange={(event) =>
                  setForm((previous) => ({ ...previous, phone: event.target.value }))
                }
                placeholder="Primary contact number"
                required
              />
              <FieldErrorText message={fieldErrors.phone ?? null} />
            </Field>

            <Field htmlFor="customer-email" label="Email">
              <TextInput
                id="customer-email"
                type="email"
                value={form.email}
                onChange={(event) =>
                  setForm((previous) => ({ ...previous, email: event.target.value }))
                }
                placeholder="Optional email"
              />
              <FieldErrorText message={fieldErrors.email ?? null} />
            </Field>

            <Field className="sm:col-span-2" htmlFor="customer-address" label="Address" required>
              <TextArea
                id="customer-address"
                value={form.address}
                onChange={(event) =>
                  setForm((previous) => ({ ...previous, address: event.target.value }))
                }
                placeholder="Present or permanent address"
                required
              />
              <FieldErrorText message={fieldErrors.address ?? null} />
            </Field>

            <Field htmlFor="customer-nid" label="NID / Passport">
              <TextInput
                id="customer-nid"
                value={form.nidOrPassport}
                onChange={(event) =>
                  setForm((previous) => ({
                    ...previous,
                    nidOrPassport: event.target.value,
                  }))
                }
                placeholder="Optional identity reference"
              />
            </Field>

            <Field htmlFor="customer-business" label="Profession / Business">
              <TextInput
                id="customer-business"
                value={form.professionOrBusiness}
                onChange={(event) =>
                  setForm((previous) => ({
                    ...previous,
                    professionOrBusiness: event.target.value,
                  }))
                }
                placeholder="Optional profession or business"
              />
            </Field>

            <Field htmlFor="customer-reference" label="Nominee / Reference">
              <TextInput
                id="customer-reference"
                value={form.nomineeOrReference}
                onChange={(event) =>
                  setForm((previous) => ({
                    ...previous,
                    nomineeOrReference: event.target.value,
                  }))
                }
                placeholder="Optional nominee or reference"
              />
            </Field>

            <Field className="sm:col-span-2" htmlFor="customer-notes" label="Notes">
              <TextArea
                id="customer-notes"
                value={form.notes}
                onChange={(event) =>
                  setForm((previous) => ({ ...previous, notes: event.target.value }))
                }
                placeholder="Internal notes"
              />
            </Field>
          </div>

          <CheckboxField
            id="customer-active"
            label="Active customer"
            description="Keep this enabled for customers who can receive new bookings."
            checked={form.isActive}
            onChange={(checked) =>
              setForm((previous) => ({ ...previous, isActive: checked }))
            }
          />

          {formError ? <Notice tone="error">{formError}</Notice> : null}

          <div className="flex flex-wrap gap-3">
            <Button disabled={isSaving} type="submit">
              {isSaving ? "Saving..." : "Create customer"}
            </Button>
            <Link href="/app/customers">
              <Button variant="secondary">Cancel</Button>
            </Link>
          </div>
        </form>
      </Card>
    </div>
  );
}
